---
# apply role 'common' to all hosts
- hosts: all
  become: true

  roles:
    - common

# web servers
- hosts: web
  become: true

  roles:
    - apache-webserver

# load balancer
- hosts: lb
  become: true
    
  roles:
    - haproxy-loadbalancer

# database
- hosts: db
  become: true

  roles:
    - mysql-database