---
# apply role 'common' to all hosts
- hosts: all
  become: true

  roles:
    - common
  tags: [ common ]

# web servers
- hosts: webservers
  become: true

  roles:
    - apache-webserver
  tags: [ webservers, web ]

# load balancer
- hosts: loadbalancer
  become: true
    
  roles:
    - haproxy-loadbalancer
  tags: [ loadbalancer, lb ]

# database
- hosts: database
  become: true
  vars_files:
    - vars/mysql.yml

  roles:
    - { role: geerlingguy.mysql }
  
  tags: [ database, db ]