---
# apply role 'common' to all hosts
- hosts: all
  become: true

  roles:
    - common

# web servers
- hosts: webservers
  become: true

  roles:
    - apache-webserver

# load balancer
- hosts: loadbalancer
  become: true
    
  roles:
    - haproxy-loadbalancer

# database
- hosts: database
  become: true

  roles:
    - mysql-database