---
# apply role 'common' to all hosts
- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  roles:
    - common

# web servers
- hosts: web
  become: true
  vars_files:
    - vars/default.yml

  roles:
    - httpd

# load balancer
- hosts: lb
  become: true
  vars_files:
    - vars/default.yml
    
  roles:
    - lb

# database
- hosts: db
  become: true
  vars_files:
    - vars/default.yml

  roles:
    - db