---
- name: Ensure HAProxy and socat are installed
  apt:
    pkg:
      - haproxy
      - socat
    state: latest
    update_cache: yes

- name: Ensure HAProxy is enabled in config
  lineinfile:
    path: /etc/default/haproxy
    regexp: "ENABLED=0"
    line: ENABLED=1
    state: present  

- name: Archive default HAProxy configuration file
  command: mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.old
  # The following ensures the command is only invoked when /etc/haproxy/haproxy.cgf exists and /etc/haproxy/haproxy.cfg.old does not
  args:
    removes: /etc/haproxy/haproxy.cfg
    creates: /etc/haproxy/haproxy.cfg.old

- name: Copy HAProxy configuration file to host
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0600
  notify: Restart HAProxy