---
# apply role 'common' to all hosts
- hosts: all
  become: true
  vars_files:
    - vars/common.yml

  roles:
    - common
  tags: [ common ]

# web servers
- hosts: webservers
  become: true
  vars_files:
    - vars/apache-webserver.yml

  roles:
    - apache-webserver
  tags: [ webservers, web ]

# load balancer
- hosts: loadbalancer
  become: true
  vars_files:
    - vars/haproxy-loadbalancer.yml
    
  roles:
    - haproxy-loadbalancer
  tags: [ loadbalancer, lb ]

# database
- hosts: database
  become: true
  vars_files:
    - vars/mysql.yml

  roles:
    - geerlingguy.mysql
    - mysql-database 
  
  tags: [ database, db ]