---
- name: Reload PostgreSQL
  service:
    name: haproxy
    state: reloaded

- name: Restart PostgreSQL
  service:
    name: haproxy
    state: restarted

- name: Start PostgreSQL
  service:
    name: haproxy
    state: started